### ISSUE TITLE
Translate celo white paper into korean

### ISSUE THREAD

**Issue by NAKsir-melody** [dsrvlabs/celo#1]

**Comment by NAKsir-melody** [comment]
[celo_white_paper_korean.pdf](https://github.com/dsrvlabs/celo-whitepaper-korean/files/3904229/celo_white_paper_korean.pdf)
first version

**Comment by jongkwang** [comment]
![Celo_TGCSO_Leaderboard_Animation](https://user-images.githubusercontent.com/897510/75876487-21c6d300-5e59-11ea-85a7-d0cb20cfa5c1.gif)
